### ISSUE TITLE
Got a question and therefore looking for contact

### ISSUE THREAD

**Issue by ithr0n** [DerEnderman/AntiSpamList#1]
Hey DerEndermann,

I am the creator of altv-minerva and I saw that you forked it.
Could you get in contact with me? I would like to ask you something...

Discord: [DE] ithr0n#5837

Thank you very much.

**Comment by DerEnderman** [comment]
Das hier ist nicht der richtige Ort um einen Issue für eine Kontaktanfrage zu stellen.
